parameters:
    opifer.eav.attribute_manager.class: Opifer\EavBundle\Model\AttributeManager
    opifer.eav.eav_manager.class: Opifer\EavBundle\Manager\EavManager
    opifer.eav.empty_value_listener.class: Opifer\EavBundle\EventListener\EmptyValueListener
    opifer.eav.discriminator_listener.class: Opifer\EavBundle\EventListener\DiscriminatorListener
    opifer.eav.form.attribute_type.class: Opifer\EavBundle\Form\Type\AttributeType
    opifer.eav.form.eav_type.class: Opifer\EavBundle\Form\Type\EavType
    opifer.eav.form.eav_post_type.class: Opifer\EavBundle\Form\Type\EavPostType
    opifer.eav.form.eav_value.class: Opifer\EavBundle\Form\Type\ValueType
    opifer.eav.form.fauxtype.class: Opifer\EavBundle\Form\Type\FauxType
    opifer.eav.form.google_address.class: Opifer\EavBundle\Form\Type\GoogleAddressType
    opifer.eav.form.option_type.class: Opifer\EavBundle\Form\Type\OptionType
    opifer.eav.form.presentationeditor.class: Opifer\EavBundle\Form\Type\PresentationEditorType
    opifer.eav.form.template_type.class: Opifer\EavBundle\Form\Type\TemplateType
    opifer.eav.form.template_object_class_type.class: Opifer\EavBundle\Form\Type\TemplateObjectClassType
    opifer.eav.form.value_provider_type.class: Opifer\EavBundle\Form\Type\ValueProviderType
    opifer.eav.form.values_subscriber.class: Opifer\EavBundle\Form\EventListener\ValuesSubscriber
    opifer.eav.form.values_type.class: Opifer\EavBundle\Form\Type\ValuesType
    opifer.eav.form.valueset_type.class: Opifer\EavBundle\Form\Type\ValueSetType
    opifer.eav.template_manager.class: Opifer\EavBundle\Model\TemplateManager
    opifer.eav.twig_extension.class: Opifer\EavBundle\Templating\TwigExtension
    opifer.eav.value_provider.pool.class: Opifer\EavBundle\ValueProvider\Pool

services:
    # Values provider pool
    opifer.eav.value_provider.pool:
        class: %opifer.eav.value_provider.pool.class%

    opifer.eav.form.values_subscriber:
        class: %opifer.eav.form.values_subscriber.class%

    # Form Types
    opifer.eav.form.eav_value:
        class: %opifer.eav.form.eav_value.class%
        arguments: [@opifer.eav.value_provider.pool]
        tags:
            - { name: form.type, alias: eav_value }

    opifer.eav.form.google_address:
        class: %opifer.eav.form.google_address.class%
        arguments: [@translator]
        tags:
            - { name: form.type, alias: google_address }

    opifer.eav.form.attribute_type:
        class: %opifer.eav.form.attribute_type.class%
        arguments: [@translator, @opifer.eav.form.option_type, %opifer_eav.attribute_class%, %opifer_eav.template_class%]
        tags:
            - { name: form.type, alias: eav_attribute }

    opifer.eav.form.template_object_class_type:
        class: %opifer.eav.form.template_object_class_type.class%
        arguments: [%opifer_eav.entities%]
        tags:
            - { name: form.type, alias: template_object_class }

    opifer.eav.form.option_type:
        class: %opifer.eav.form.option_type.class%
        arguments: [%opifer_eav.option_class%]
        tags:
            - { name: form.type, alias: eav_option }

    opifer.eav.form.value_provider_type:
        class: %opifer.eav.form.value_provider_type.class%
        arguments: [@opifer.eav.value_provider.pool]
        tags:
            - { name: form.type, alias: value_provider }

    opifer.eav.form.presentationeditor:
        class: %opifer.eav.form.presentationeditor.class%
        tags:
            - { name: form.type, alias: presentationeditor }

    opifer.eav.form.fauxtype:
        class: %opifer.eav.form.fauxtype.class%
        tags:
            - { name: form.type, alias: eav_faux }

    opifer.eav.form.eav_type:
        class: %opifer.eav.form.eav_type.class%
        arguments: [@router]
        tags:
            - { name: form.type, alias: eav }

    opifer.eav.form.eav_post_type:
        class: %opifer.eav.form.eav_post_type.class%
        arguments: [@router]
        tags:
            - { name: form.type, alias: eav_post }

    opifer.eav.form.template_type:
        class: %opifer.eav.form.template_type.class%
        arguments: [@translator, @opifer.eav.form.attribute_type, %opifer_eav.template_class%]
        tags:
            - { name: form.type, alias: eav_template }

    opifer.eav.form.valueset_type:
        class: %opifer.eav.form.valueset_type.class%
        arguments: [%opifer_eav.valueset_class%]
        tags:
            - { name: form.type, alias: opifer_valueset }

    opifer.eav.form.values_type:
        class: %opifer.eav.form.values_type.class%
        arguments: [@opifer.eav.form.values_subscriber]
        tags:
            - { name: form.type, alias: values_collection }

    # Entity Managers
    opifer.eav.attribute_manager:
        class: %opifer.eav.attribute_manager.class%
        arguments: [@doctrine.orm.default_entity_manager, %opifer_eav.attribute_class%]

    opifer.eav.eav_manager:
        class: %opifer.eav.eav_manager.class%
        arguments: [@opifer.eav.value_provider.pool, %opifer_eav.valueset_class%]

    opifer.eav.template_manager:
        class: %opifer.eav.template_manager.class%
        arguments: [@doctrine.orm.default_entity_manager, %opifer_eav.template_class%]

    # Listeners
    opifer.eav.discriminator_listener:
        class: %opifer.eav.discriminator_listener.class%
        arguments: [@opifer.eav.value_provider.pool]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    opifer.eav.empty_value_listener:
        class: %opifer.eav.empty_value_listener.class%
        arguments: [@opifer.eav.eav_manager]
        tags:
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: postPersist }

    # Twig Extension
    opifer.eav.twig_extension:
        class: %opifer.eav.twig_extension.class%
        arguments: [@form.factory, @opifer.eav.eav_manager]
        tags:
            - { name: twig.extension }
